### ISSUE TITLE
Add methods for returning rows, columns, squares from board class

### ISSUE THREAD

**Issue by dombas** [dombas/sudoku-cpp#12]
Methods that will return a 1d array with digits from a given row, column or square.
A square is a 3x3 part of the board. The board is made up of 9 such squares.

For example the first square will have digits with the following indexes (row, column):
(0, 0), (0, 1), (0, 2)
(1, 0), (1, 1), (1, 2)
(2, 0), (2, 1), (2, 2)

The digits should be returned in the order left to right, top to bottom.
From a square for example:
1,2,3
4,5,6
7,8,9
the returned array should be:
[1,2,3,4,5,6,7,8,9]

**Comment by Iswara97** [comment]
Hi, 

I can work on this issue. I just wanted to clarify will there be 3 or 9 squares in total on the board? I believe we have to index the squares by columns (0..2) and row (0..2), correct?

Thanks.

**Comment by dombas** [comment]
Oh, my mistake, there should indeed be 9 squares, not 3, good catch. I'll fix the description. 
Yes, I think addressing the squares as a 3x3 table will work.
We may also need a method to translate a single cell's address(row, col) into a corresponding square's,  but that can be done in another issue.

**Comment by Iswara97** [comment]
Hi, 

So I was able to pull the code and add the new features, but when I tried to push the new branch with an authentication token, I got an error "unable to access 'https://github.com/dombas/sudoku-cpp.git/': The requested URL returned error: 403". Would this have to do the permission on the repo? 

I wasn't too sure as this is my first issue on here. 

Thanks.

**Comment by dombas** [comment]
This is because you don't have direct access to this repository.

The usual way to contribute to open source projects is to make a fork, make some changes and make a pull request.

Here's an article 
https://guides.github.com/activities/forking/
