### ISSUE TITLE
Add a is_valid() method to Board

### ISSUE THREAD

**Issue by dombas** [dombas/sudoku-cpp#23]
The method should check for multiple occurrences of field values (1-9) in each row, column and square.
Only empty field is okay to have multiples of.
Return false, if there are any multiples.
Return true, if there is at most 1 occurrence of each value.

Examples:
[0,0,0,1,6,3,0,4,0] - true (multiples of 0 - empty field - are okay)
[1,0,2,3,4,5,6,7,1] - false (there are multiples of 1)

**Comment by Iswara97** [comment]
Hi, I can work on this issue.
